export const SET_ORDER = 'SET_ORDER'
export const SET_ORDER_LIST = 'SET_ORDER_LIST'
export const SET_SUPPPLIER_ORDER = 'SET_SUPPPLIER_ORDER'

export const STATUS_CREATED = 'Created'
export const STATUS_PLANNING = 'Planning'
export const STATUS_PLANNED = 'Planned'
export const STATUS_IN_TRANSIT = 'InTransit'
export const STATUS_ARRIVED = 'Arrived'
export const STATUS_CANCELED = 'Canceled'